#################################################
################# MONGODB #######################
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://localhost:27017/cryptocurrency
      repositories:
        enabled: true